# syntax=docker/dockerfile:1

FROM python:3.12-slim

# ---- env ----
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1 \
    SIGNALS_DB_PATH=/data

# ---- system deps (keep minimal) ----
# (SQLite is built into Python; this is mostly for certificates + basic tooling)
RUN apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# ---- app directories ----
WORKDIR /app

# Create a writable data dir for sqlite db + WAL files
RUN mkdir -p /data

# Create non-root user
RUN useradd -m -u 10001 appuser \
 && chown -R appuser:appuser /app /data

# ---- install deps ----
# Copy only dependency manifests first for better layer caching
COPY requirements/requirements.txt ./requirements/requirements.txt
COPY pyproject.toml ./

RUN python -m pip install --upgrade pip \
 && python -m pip install -r requirements/requirements.txt

# ---- copy app code ----
COPY src ./src
COPY scripts ./scripts
COPY requirements ./requirements
COPY README.md .

# If you need your kafka *.properties at runtime and they are generated by script,
# keep scripts in image. Otherwise you can omit scripts copy.

USER appuser

# ---- default command ----
# Your main.py is at src/main.py based on your screenshot.
# If it lives under a package, adjust accordingly.
CMD ["python", "-m", "src.main"]
